# LILYGO T-HiGrow sensor device

# Change the devicename and devicename_short to something aking
# to the name ESPhome has given the device after discovery.

# Sleep duration has been set so that when the device is woken
# with the wakup_button there is a 5 minute window to reflash
# the software.

substitutions:
  devicename: esphome-web-1d7610
  devicename_short: Grow_1d7610
  pin_sda: GPIO25
  pin_scl: GPIO26
  pin_sensor_power: GPIO4
  pin_wakeup_button: GPIO35
  pin_dht_sensor: GPIO16
  pin_adc_soil_moisture: GPIO32
  pin_adc_battery: GPIO33
  pin_adc_salt: GPIO34
  sleep_time_minutes: 30min
  wake_time_seconds: 20s
  measure_interval_seconds: 1s
  
# Enable logging
logger:
  level: debug

esphome:
  name: $devicename
  platform: ESP32
  board: lolin_d32
  on_boot:
    priority: 900
    then:
      - delay: 3s
      - switch.turn_on: spower
      - logger.log: "On-board sensors have been powered on"
      - delay: 3s
      - lambda: |-
          Wire.begin();
      - delay: 2s
  on_shutdown:
    then:
      - switch.turn_off: spower
      - logger.log: "On-board sensors have been powered off"

# Enable Home Assistant API
api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: $devicename_short
    password: !secret wifi_ap_password

captive_portal:

i2c:
  sda: $pin_sda
  scl: $pin_scl
  scan: True
  id: bus_a
  setup_priority: 0

deep_sleep:
  sleep_duration: $sleep_time_minutes
  id: deep_sleep_system
  wakeup_pin: $pin_wakeup_button
  wakeup_pin_mode: INVERT_WAKEUP
  run_duration: 
    default: $wake_time_seconds
    gpio_wakeup_reason: 5min

switch:
  - platform: gpio
    pin: $pin_sensor_power
    name: $devicename_short Sensor Power
    id: spower
    restore_mode: ALWAYS_OFF
    internal: true

binary_sensor:
  - platform: gpio
    pin: 
      number: $pin_wakeup_button
      inverted: True
    name: $devicename_short Wakeup Button
  - platform: template
    device_class: battery_charging
    name: $devicename_short Charging
    id: charging
  - platform: template
    device_class: battery
    name: $devicename_short Low Battery
    id: lowbatt
      
sensor:
  - platform: dht
    model: dht11
    pin:
      number: $pin_dht_sensor
      mode: input
    temperature:
      name: $devicename_short Air Temperature
      accuracy_decimals: 1
      filters:
        - sliding_window_moving_average:
            window_size: 21
            send_every: 9
            send_first_at: 9
    humidity:
      name: $devicename_short Air Humidity
      accuracy_decimals: 1
      filters:
        - sliding_window_moving_average:
            window_size: 21
            send_every: 9
            send_first_at: 9
    update_interval: $measure_interval_seconds
    setup_priority: -100
    
  - platform: adc
    pin: $pin_adc_soil_moisture
    name: $devicename_short Soil Moisture
    update_interval: $measure_interval_seconds
    unit_of_measurement: '%'
    accuracy_decimals: 0
    filters:
      - calibrate_linear:
          - 1.1 -> 0.0
          - 0.0 -> 100.0
      - quantile:
          window_size: 21
          send_every: 11
          send_first_at: 11
          quantile: .9
    
  - platform: adc
    pin: $pin_adc_salt
    name: $devicename_short Salt
    update_interval: 1s
    unit_of_measurement: '%'
    accuracy_decimals: 1
    filters:
      - calibrate_linear:
          # Map 0.0 (from sensor) to 0.0 (true value)
          - 0.0 -> 0.0
          - 1.1 -> 100.0
      - sliding_window_moving_average:
          window_size: 15
          send_every: 7
          send_first_at: 7
    
  - platform: adc
    pin: $pin_adc_battery
    name: $devicename_short Battery
    id: battery
    attenuation: 11db
    unit_of_measurement: 'V'
    update_interval: $measure_interval_seconds
    accuracy_decimals: 3
    filters:
      - lambda: >
          float VREF = 1.1;
          float batt = (x / 4.095) * 6.6 * VREF;
          if (batt > 1.0) return batt;
          else return {};
      - filter_out: NaN
      - sliding_window_moving_average:
          window_size: 21
          send_every: 9
          send_first_at: 9
    on_value:
      - lambda: >
          if (x > 4.0) {
            id(charging).publish_state(true);
            id(deep_sleep_system).prevent_deep_sleep();
          }
          else {
            id(charging).publish_state(false);
            // id(deep_sleep_system).allow_deep_sleep();
          }
          if (x < 2.5) id(lowbatt).publish_state(true);
          else id(lowbatt).publish_state(false);

  - platform: bh1750
    i2c_id: bus_a
    name: $devicename_short Illuminance
    address: 0x23
    update_interval: $measure_interval_seconds
    accuracy_decimals: 1
    setup_priority: -200
    filters:
      - sliding_window_moving_average:
          window_size: 21
          send_every: 9
          send_first_at: 9
